server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

#datasource
  datasource:
    name: masterDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.104:3306/libra
    username: root
    password: 12345

mybatis:
  mapper-locations: com.dream.libra.mapper/*.xml
  configuration:
      map-underscore-to-camel-case : true